### PR TITLE
Support for varargs in generic

### LINKED ISSUE #327: `Generic` instances generation for case classes with varargs
Currently shapeless can't generate `Generic` instances for case classes with variable arguments:
```
scala> import shapeless._
import shapeless._

scala> case class A(x: Int, ys: String*)
defined class A

scala> Generic[A]
<console>:13: shapeless.this.Generic.materialize is not a valid implicit value for shapeless.Generic[A] because:
hasMatchingSymbol reported error: type mismatch;
 found   : String
 required: String*
              Generic[A]
                     ^
<console>:13: error: could not find implicit value for parameter gen: shapeless.Generic[A]
              Generic[A]
                     ^
```

Maybe it makes sense to treat the last argument as `Seq[_]` or something like that.

### PR DESCRIPTION
**Pull request by netvl**
Fixed #327 

Turned out it wasn't so difficult.

### CODE REVIEW

**Comment by netvl** [comment]
The only problem is that scalac seems to be unable to handle `Generic` instances for case classes with varargs when used in console:
```
scala> case class A(xs: String*)
defined class A

scala> Generic[A]
java.lang.AssertionError: assertion failed: scala.type
        at scala.reflect.internal.tpe.TypeMaps$adaptToNewRunMap$.adaptToNewRun(TypeMaps.scala:1093)
        at scala.reflect.internal.tpe.TypeMaps$adaptToNewRunMap$.apply(TypeMaps.scala:1137)
        at scala.reflect.internal.tpe.TypeMaps$adaptToNewRunMap$.apply(TypeMaps.scala:1066)
        at scala.collection.immutable.List.loop$1(List.scala:173)
        at scala.collection.immutable.List.mapConserve(List.scala:189)
        at scala.reflect.internal.tpe.TypeMaps$adaptToNewRunMap$.apply(TypeMaps.scala:1135)
        at scala.reflect.internal.Symbols$Symbol.adaptInfos(Symbols.scala:1611)
        at scala.reflect.internal.Symbols$Symbol.rawInfo(Symbols.scala:1563)
        at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1493)
        at scala.reflect.internal.tpe.TypeMaps$TypeMap.loop$1(TypeMaps.scala:227)
        at scala.reflect.internal.tpe.TypeMaps$TypeMap.noChangeToSymbols(TypeMaps.scala:229)
        at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:243)
        at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:235)
        at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:158)
        at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.apply(TypeMaps.scala:484)
        at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:138)
        at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.apply(TypeMaps.scala:484)
        at scala.reflect.internal.Types$Type.asSeenFrom(Types.scala:663)
        at scala.reflect.internal.Types$Type.computeMemberType(Types.scala:698)
        at scala.reflect.internal.Symbols$MethodSymbol.typeAsMemberOf(Symbols.scala:2913)
        at scala.reflect.internal.Types$Type.memberType(Types.scala:689)
        at scala.tools.nsc.typechecker.Infer$Inferencer.checkAccessible(Infer.scala:272)
        at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$makeAccessible(Typers.scala:555)
        at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$102.apply(Typers.scala:4732)
        at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$102.apply(Typers.scala:4732)
        at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:676)
        at scala.tools.nsc.typechecker.Typers$Typer.typedSelectInternal$1(Typers.scala:4732)
        at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedSelect$1(Typers.scala:4657)
        at scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:4796)
        at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5321)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5337)
        at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5373)
        at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5400)
        at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5347)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5351)
        at scala.tools.nsc.interpreter.ReplGlobal$$anon$1$$anon$2.typed(ReplGlobal.scala:36)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5440)
        at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:5531)
        at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:879)
        at scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1381)
        at scala.tools.nsc.typechecker.Namers$Namer.getSig$1(Namers.scala:1532)
        at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1541)
        at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply$mcV$sp(Namers.scala:781)
        at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:780)
        at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:780)
        at scala.tools.nsc.typechecker.Namers$Namer.scala$tools$nsc$typechecker$Namers$Namer$$logAndValidate(Namers.scala:1568)
        at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:780)
        at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:772)
        at scala.tools.nsc.typechecker.Namers$$anon$1.completeImpl(Namers.scala:1684)
        at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter$class.complete(Namers.scala:1692)
        at scala.tools.nsc.typechecker.Namers$$anon$1.complete(Namers.scala:1682)
        at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1483)
        at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1628)
        at scala.tools.nsc.typechecker.MethodSynthesis$MethodSynth$class.addDerivedTrees(MethodSynthesis.scala:181)
        at scala.tools.nsc.typechecker.Namers$Namer.addDerivedTrees(Namers.scala:53)
        at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$25.apply(Typers.scala:1890)
        at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$25.apply(Typers.scala:1890)
        at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$rewrappingWrapperTrees$1.apply(Typers.scala:1827)
        at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$rewrappingWrapperTrees$1.apply(Typers.scala:1824)
        at scala.collection.immutable.List.flatMap(List.scala:327)
        at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1890)
        at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1790)
        at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5287)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5336)
        at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5373)
        at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5400)
        at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5347)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5351)
        at scala.tools.nsc.interpreter.ReplGlobal$$anon$1$$anon$2.typed(ReplGlobal.scala:36)
        at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5429)
        at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:3028)
        at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$62.apply(Typers.scala:3132)
        at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$62.apply(Typers.scala:3132)
        at scala.collection.immutable.List.loop$1(List.scala:173)
        at scala.collection.immutable.List.mapConserve(List.scala:189)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3132)
        at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:4989)
        at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5289)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5336)
        at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5373)
        at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5400)
        at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5347)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5351)
        at scala.tools.nsc.interpreter.ReplGlobal$$anon$1$$anon$2.typed(ReplGlobal.scala:36)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5425)
        at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:102)
        at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:441)
        at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:432)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:441)
        at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:94)
        at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:93)
        at scala.collection.Iterator$class.foreach(Iterator.scala:750)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
        at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1500)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1487)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1482)
        at scala.tools.nsc.interpreter.IMain.compileSourcesKeepingRun(IMain.scala:425)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compileAndSaveRun(IMain.scala:841)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compile(IMain.scala:800)
        at scala.tools.nsc.interpreter.IMain$Request$$anonfun$compile$1.apply$mcZ$sp(IMain.scala:993)
        at scala.tools.nsc.interpreter.IMain$Request$$anonfun$compile$1.apply(IMain.scala:993)
        at scala.tools.nsc.interpreter.IMain$Request$$anonfun$compile$1.apply(IMain.scala:993)
        at scala.tools.nsc.interpreter.IMain$$anonfun$withoutWarnings$1.apply(IMain.scala:102)
        at scala.tools.nsc.interpreter.IMain.beQuietDuring(IMain.scala:210)
        at scala.tools.nsc.interpreter.IMain.withoutWarnings(IMain.scala:97)
        at scala.tools.nsc.interpreter.IMain$Request.compile$lzycompute(IMain.scala:993)
        at scala.tools.nsc.interpreter.IMain$Request.compile(IMain.scala:971)
        at scala.tools.nsc.interpreter.IMain.compile(IMain.scala:568)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:556)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:554)
        at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:802)
        at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:847)
        at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:705)
        at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:404)
        at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:430)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:918)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:904)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:904)
        at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
        at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:904)
        at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:929)
        at xsbt.ConsoleInterface.run(ConsoleInterface.scala:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
        at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:76)
        at sbt.Console.sbt$Console$$console0$1(Console.scala:22)
        at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:23)
        at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
        at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
        at sbt.Logger$$anon$4.apply(Logger.scala:85)
        at sbt.TrapExit$App.run(TrapExit.scala:248)
        at java.lang.Thread.run(Thread.java:745)
```

I have no idea what the problem is but outside of scala console it works perfectly (as is demonstrated in tests).

**Comment by milessabin** [comment]
I'm slightly reluctant to merge this with the REPL issue. Any chance you could take another look at it?

**Comment by netvl** [comment]
@milessabin, playing with this a little more, I've found out a funny thing: while `Generic[A]` fails with the above message, `implicitly[Generic[A]]` does work:
```scala
scala> implicitly[Generic[A]]
res0: shapeless.Generic[A] = fresh$macro$2$1@47d79f76
```

Obtaining the output of the macro with `-Ymacro-debug-lite`, fixing it slightly and pasting it into REPL works as well.

I have no idea what's happening except that this is likely a compiler bug.

**Comment by netvl** [comment]
@milessabin, bump.

Should I do something else here?

**Comment by milessabin** [comment]
I guess I'm a little reluctant to merge this if it reliably crashes the REPL. It could be a REPL-specific compiler bug (if it goes away with Scala 2.11.6 that would be the most likely explanation).

**Comment by milessabin** [comment]
REPL crash persists in Scala 2.11.6, but I have a fix, so I'll be merging a tweaked version of this very shortly ... many thanks!

**Comment by milessabin** [comment]
I rebased and merged locally ... it's now in ... thanks again :-)

The REPL crasher fix is here: https://github.com/milessabin/shapeless/commit/4760b0357de72315fd4f8b30b4c366a1fd3c1e46.

**Comment by netvl** [comment]
Wow! The fix looks like a total magic to me. How did you know it would fix it?

**Comment by milessabin** [comment]
I took a look at the assert in the scalac sources and that made me suspicious of the `typeOf[Seq[_]]`. Changing that didn't help on it's own, but while staring at that line in your PR it struck me that `appliedType` would be more appropriate in this context anyway.

So a mixture of gut feeling and luck I guess ;-)

**Comment by netvl** [comment]
Oh, thanks for the explanation! I'm not that familiar with scala macros with their massive and almost undocumented API, so I just found the code to do it somewhere on the web. Great to know that there is a better way.

**Pull request closed without merging**
