### PR TITLE
Add DropRange typeclass for HList and Tuple

### PR DESCRIPTION
**Pull request by Ssstlis**
Hi!
I just add two typeclasses for HList and Tuple ops.
My motivation is to create DropRange with it's behavior to use it something like this between two classes:
```scala
//Demo
final case class A(
  a: String,
  b: Boolean,
  c: Int,
  d: DateTime
)

final case class B(
  a: String,
  d: DateTime
)

val a: A = A("", false, 0, DateTime.now())
val b: B =  Generic[B].from(Generic[A].to(a).dropRange(2, 3))
```

### CODE REVIEW

**Comment by Ssstlis** [comment]
I'd be appreciate for @joroKr21 review =)

**Comment by joroKr21** [comment]
Sorry, still pondering. I'm afraid of bloating the API.
In general I have no objections to adding type level versions of std lib collection methods.
But this is not one of them so I'm not sure.

@milessabin WDYT?

**Comment by milessabin** [comment]
I'm a bit puzzled by `DropAt` ... how does it differ from `Drop`?

**Comment by Ssstlis** [comment]
Yes, you're right, i missed that typeclass. I'll remove it from PR.

**Comment by milessabin** [comment]
Thanks.

I guess I'm of the same mind as @joroKr21. It would help tip me in favour if you could describe a compelling example of it in use.

**Review by milessabin — APPROVED** [review]
LGTM!

**Comment by joroKr21** [comment]
I'm mildly 👎 due to the reasons already stated

**Comment by milessabin** [comment]
Yes, sorry, I approved in error.

I think we should close this now.

**Pull request closed without merging**
