### PR TITLE
Document Witness

### PR DESCRIPTION
**Pull request by dwijnand**
(Nerd-sniping Miles into documenting these awesome features!)

### CODE REVIEW

**Comment by notxcain** [comment]
:rocket:

**Comment by milessabin** [comment]
It isn't strictly speaking an implementation of SIP-23, although it does cover the same ground (sorry if I was misleading earlier). I think it would be better to say something like "See SIP-23 for a related proposed language change".

**Comment by dwijnand** [comment]
Amended.

**Comment by milessabin** [comment]
Many thanks! Merged :-)

**Pull request merged**
