### PR TITLE
Remove faulty implementation of Coproduct ZipOne

### LINKED ISSUE #772: ZipOne on coproducts throws runtime exceptions in most cases
Coproduct ops include a `ZipOne` typeclass, witnessing that zipping two coproducts is the coproduct of tuples of elements taken pairwise, e.g. 
```scala
ZipOne[Int :+: String :+CNil, Boolean :+: Double :+: CNil]
res0: ZipOne {type Out = (Int, Boolean) :+: (String, Double) :+: CNil
```
However, this evidence is clearly false, as you can't guarantee that you'll always have both elements when you zip. Matter of fact, it only compiles due to the use of  `Option#get` on the Coproduct head.

As a result, if you pass in anything but two `Inl`, it throws an exception.

Is this intended behaviour? Imho this op should either be removed, or changed to return a more meaningful type, i.e. a Coproduct of cats `Ior`. WDYT?

### PR DESCRIPTION
**Pull request by SystemFw**
Fixes #772. Obviously breaks binary compatibility.

### CODE REVIEW

**Comment by SystemFw** [comment]
Is there anything holding this PR back? The removed code compiles but crashes at runtime, very non-shapeless behaviour :)

**Comment by milessabin** [comment]
Sorry, it looks like this slipped though the cracks ... could you fix up the MiMa failures?

**Comment by SystemFw** [comment]
Ehm, the failure is due to the fact that the typeclass is removed. Can one preserve binary compatibility when removing something? (If yes, I'll research and fix it)

**Comment by milessabin** [comment]
You can add a MiMa exclusion for the removed type.

**Comment by SystemFw** [comment]
Cool, I'll look into that and fix it. A bit busy at the moment but I'll get to it

**Comment by SystemFw** [comment]
@milessabin this should be all ready now

**Comment by milessabin** [comment]
Awesome! Many thanks ... merging :-)

**Pull request merged**
