### PR TITLE
Short-circuit HList / Coproduct implicit recursion via a macro-backed type class

### PR DESCRIPTION
**Pull request by alexarchambault**
Closed https://github.com/milessabin/shapeless/pull/459 by mistake, reopening it here.

### CODE REVIEW

**Comment by alexarchambault** [comment]
Still need some work.

**Comment by milessabin** [comment]
We could have a look at it during the Scala eXchange hack day if you're around.

**Comment by milessabin** [comment]
Is this redundant now?

**Comment by alexarchambault** [comment]
It's not really redundant. It's something that short-circuits standard (recursive) derivation for case classes / ADTs, when using `TypeClass`.

I don't have much time for it right now, I think that can wait... (I can close and re-open it later if you'd like.)

**Comment by milessabin** [comment]
I'll punt this to 2.3.1 ...

**Comment by milessabin** [comment]
Do you think you'll have any time for this for 2.3.2?

**Comment by alexarchambault** [comment]
I'd be willing to have a look at it, yes (some type class derivation slowness bite me quite hard very recently...). I'll update the PR in a few days.

**Comment by alexarchambault** [comment]
Updated the PR.

I may try to make this mechanism more general in a second time (like https://github.com/milessabin/shapeless/pull/459 was at some point). So that it can handle default values or require extra auxiliary type class instances for each field / constructor - if you're fine with it.

**Comment by alexarchambault** [comment]
I haven't tried to benchmark that in its current state (although there's no reason it doesn't make things better).

**Comment by alexarchambault** [comment]
Note that it uses `Console.err.println` to explicitly report which field or constructor is making the derivation fail (which helps a great deal to debug derivations). `c.error` or `c.warning` are silenced here.

**Comment by alexarchambault** [comment]
This seems to break the orphan tests, for reasons that are unclear to me... I don't much about their internals. Aren't they supposed to be deprecated somehow (by export-hook, or `LowPriority` here)? If that's the case, I'd rather wait for shapeless 2.4. I'm not sure there's a real problem in `Derived` here (and in any case, that can be more thoroughly tested in the mean time).

**Comment by milessabin** [comment]
Am I dreaming, or has this PR (and some others) mysteriously come back from the dead?

**Comment by milessabin** [comment]
I'm going to close this for now. I don't want to add new macros to shapeless at this point and I think that `-Yinduction-heuristics` is the better way forward.

**Pull request closed without merging**
