### PR TITLE
Add Default type class

### PR DESCRIPTION
**Pull request by alexarchambault**
Fixes https://github.com/milessabin/shapeless/issues/461

### CODE REVIEW

**Comment by alexarchambault** [comment]
Beware that a test that I would expect to fail ([`Default[AnyRef]`](https://github.com/alexarchambault/shapeless/commit/08dd3c102326acbff2745094bcc8d4b8e093db84#diff-e62c779b4e79399cb728676a9c58e196R40)), actually passes. This should be related to https://github.com/milessabin/shapeless/issues/453.

**Comment by milessabin** [comment]
+1 for creative use of `None.type` and `Some[t]`.

I wonder, though, if it wouldn't be better to return a record containing only fields for the default values which are present? Then it would be possible to use the record `Merge` operation to combine defaults with, eg., the records produced by `RecordArgs`.

**Comment by travisbrown** [comment]
+1, this is great.

I don't have strong opinions on the representation. In general it seems likely that returning a record would be more convenient, but in the case of circe in particular I don't think there'd be much of a difference in ease of implementation, and this representation might actually be a little nicer.

**Comment by milessabin** [comment]
@travisbrown that's good enough for me ... merging :-)

**Comment by fommil** [comment]
:+1:

**Pull request merged**
