### PR TITLE
Use MemberScopeApi#sorted where necessary

### LINKED ISSUE #576: Use MemberScopeApi.sorted where necessary
As discussed in #575, members in a scope (as returned by, e.g., `Type.decls`) are not guaranteed to be in declaration order. To guarantee this, `MemberScopeApi.sorted` can be used. According to @milessabin there can be other places where this may be necessary. This issue is to track changing them to use `.sorted`.

### PR DESCRIPTION
**Pull request by durban**
I added the .sorted call where it seemed to make sense. Should fix #576.

### CODE REVIEW

**Comment by milessabin** [comment]
Could you remind me of the discussion? Just looking at these quickly it's not immediately obvious to me that sorting makes any semantic difference.

**Comment by alexarchambault** [comment]
Or add a test to illustrate the difference (if any)?

**Comment by durban** [comment]
I don't think there is a difference in practice, it's just that the items in `Type.decls` are not guaranteed to be in (source) declaration order. In practice, they _seem_ to be; but with the `.sorted` call, they are now _guaranteed_ to be. (See also #576 and #575.)

**Comment by milessabin** [comment]
In the first and last case in your commit there would only be a difference if there was more than one match. Should it be an error if that's the case? In the second case I don't think sort order is relevant?

**Comment by durban** [comment]
Hm, right, the first and last should have at most one match. The last already seem to check this (`productCtorsOf(tpe).size == 1`). The first one doesn't (although I don't think it can happen that there are more). So you're right, these shouldn't necessarily be sorted.

The second case (if I'm not mistaken) seems to collect the fields of a (e.g.) case class for `Generic`. In this case, I think order could matter?

**Comment by durban** [comment]
I've updated my commit, and removed the original first and last modification. Now only the one in `fieldsOf` remains, which I still think makes sense.

**Comment by milessabin** [comment]
My sincere apologies for taking to long to review and merge this :-(

Anyhow, LGTM. Many thanks ... merging :-)

**Pull request merged**
