### PR TITLE
ZipWithIndex with O(n) implicit search complexity

### PR DESCRIPTION
**Pull request by alexarchambault**
Looks like no one is taking a cut at https://github.com/milessabin/shapeless/issues/490, so here I go :-)

### CODE REVIEW

**Comment by AndreasKostler** [comment]
LGTM :+1:
However, could you explain to me as to why the original version exhibited the slow behaviour while this version doesn't. We can take this offline if you like, just find me on gitter.

**Comment by alexarchambault** [comment]
Maybe not a problem of some kind of "implicit search complexity" after all, but this implementation just more simple, not resorting to `Zip`, itself resorting to `Transposer` that I find hard to get one's head around to. I can easily call it on HLists of length ~70 (before seeing other unrelated scalac crashes).

**Comment by alexarchambault** [comment]
Argh, merged by mistake :-(

**Comment by alexarchambault** [comment]
Ping me to re-open :-|

**Comment by jarreds** [comment]
@alexarchambault +1 on reopening. I'd like to use `zipWithIndex` but can't until something like this in place.

**Comment by alexarchambault** [comment]
@AndreasKostler My changes make it look (almost) like the dual of what *you* did for coproducts.

**Comment by AndreasKostler** [comment]
@alexarchambault I still have to get my head around as to why the exponential compile time happens. Neither `Range` nor `Zip` exhibit this behaviour and I can't see why `zipWithIndex` would...any light on this is highly appreciatetd

**Pull request merged**
