### PR TITLE
Add GT for Nat

### PR DESCRIPTION
**Pull request by ryoppy**

### CODE REVIEW

**Comment by milessabin** [comment]
Thanks for the PR!

Did you investigate defining `GT[A, B]` and `GTEq[A, B]` in terms of `LTEq[B, A]` and `LT[B, A]` respectively?

**Comment by ryoppy** [comment]
thank you for your comments!
yes, I thought GT is (a little) useful. but unnecessary?

**Comment by milessabin** [comment]
I was thinking that you could define them via type aliases rather than reproducing the induction from `LT` and `LTEq`, ie.

```scala
type GT[A, B] = LTEq[B, A]
type GTEq[A, B] = LT[B, A]
```

**Comment by ryoppy** [comment]
thx! cool!
I tried refactoring.

**Comment by milessabin** [comment]
LGTM ... Many thanks! ... Merging :-)

**Pull request merged**
