### PR TITLE
Fully qualify scala.Symbol in quasiquote

### PR DESCRIPTION
**Pull request by fthomas**

### CODE REVIEW

**Comment by fthomas** [comment]
This looked like a hygiene issue to me, but apparently it is not. I don't know why `scala.Symbol` cannot fully qualified in this extractor quasiquote.

**Comment by milessabin** [comment]
I agree it looks suspicious. I can't remember now if it was deliberate. Were you able to come up with a use site example of unhygiene?

**Comment by fthomas** [comment]
No, I haven't observed any problems at the use site yet. I'll further investigate and report my findings here. In the meantime, feel free to close this PR.

**Comment by milessabin** [comment]
OK, thanks for investigating :-)

**Pull request closed without merging**
