### PR TITLE
unwrap tag (tagged)

### PR DESCRIPTION
**Pull request by etaty**
I was trying to play with tagged type 
https://gitter.im/milessabin/shapeless?at=56ab8938dc33b33c7548a5a2

### CODE REVIEW

**Comment by clhodapp** [comment]
Can you add a test similar to https://github.com/etaty/shapeless/blob/features/tagged-unwrap/core/src/test/scala/shapeless/unwrapped.scala#L109 ? I'm concerned about whether it will pass.

**Comment by etaty** [comment]
Yep good catch.
`test.illTyped("unwrapped: String @@ TestTag")` don't work
unless I write
`val unwrapped : String = wrapped.unwrap`

**Comment by etaty** [comment]
that's weird, I am curious for the reason why it keeps the tagged type.

**Comment by clhodapp** [comment]
It's because e.g. `String @@ TestTag` is the most-specific `T` that can be extracted from `T @@ TestTag`, so that's what the compiler chooses to infer (as strange as it is, `(String @@ TestTag) @@ TestTag` is actually the same as `String @@ TestTag` and the compiler is able to see that this is the case and reason from it). As far as I currently know, you actually need to be working in the context of a macro to actually strip tags off in the general case, such as what's needed here.

**Comment by clhodapp** [comment]
Also, the version of this in your PR actually leaves off the maybe-important feature of being able to see through multiple wrappers over the same type. This is the purpose of all of those `chain` parameters in the other instance providers. Also, rather than constructing a new instance, you can take advantage of the micro-optimization I make in some of my other instances: Taking an `implicit chain` and simply casting it. This works because Unwrapped instances for e.g. tagged types don't have to actually change the object, they just need to make the types line up.

**Comment by milessabin** [comment]
What's the status of this? I'm aiming for an RC1 before the end of the week and it'd be nice if we could get this in by then.

**Comment by etaty** [comment]
Hi Miles,
I know nothing about macro.
And I did not realise that in my case, I did not need the `unwrap`. (I am also not sure it is a needed feature).
So I won't probably finish the pull-request by the end of the week.
(you can close/reject)

**Comment by milessabin** [comment]
No worries ... if you'd like to work on this I'll punt it to 2.3.1?

**Comment by milessabin** [comment]
Moved to 2.3.1 ...

**Comment by clhodapp** [comment]
Just got around to checking how easy it is to define an untagger with Mile's higher order unification patch (https://github.com/scala/scala/pull/5102). It's pretty easy, I think: https://gist.github.com/clhodapp/a2f1b6fc011df9b60b107bd3034aef6d

**Comment by clhodapp** [comment]
Actually, that technique seems to work even without higher order unification!

**Comment by clhodapp** [comment]
https://gist.github.com/clhodapp/3862b54ddda3dc45a581b1733342a7bc

**Comment by milessabin** [comment]
Do either or both of you have time to try and get this over the finish line for 2.3.1?

**Comment by clhodapp** [comment]
I'll make a PR this evening or next.

**Comment by milessabin** [comment]
Oh, blimey! Missed this ... sorry :-(

LGTM. Many thanks ... merging :-)

**Pull request merged**
