### PR TITLE
Fix lens example

### PR DESCRIPTION
**Pull request by 3tty0n**
Fix typo, and modified some lenses in accordance with the wiki (https://github.com/milessabin/shapeless/wiki/Feature-overview:-shapeless-2.0.0#boilerplate-free-lenses-for-arbitrary-case-classes)

### CODE REVIEW

**Comment by milessabin** [comment]
Thanks!

The spelling correction ("Lense" -> "Lens") is good ... mea culpa.

The examples are correct as they are though, and it would be better to update the wiki to match rather than the other way around.

**Comment by 3tty0n** [comment]
Thank you for replying for my PR. For now, I will fix only typo.

**Comment by 3tty0n** [comment]
I have fixed typo ("Lense" -> "Lens").

**Comment by milessabin** [comment]
Many thanks ... merging :-)

**Pull request merged**
