### PR TITLE
rebasing wip/smc with master

### PR DESCRIPTION
**Pull request by stacycurl**

### CODE REVIEW

**Comment by milessabin** [comment]
Hmm ... don't you think it would be better to just rebase this directly?

**Comment by stacycurl** [comment]
Do you mean without a PR ?

**Comment by milessabin** [comment]
Yup.

**Comment by milessabin** [comment]
OK, I've rebased the branch directly and force pushed ...

**Comment by stacycurl** [comment]
Thanks, turns out neglect does work :P

On 26 February 2015 at 12:00, Miles Sabin <notifications@github.com> wrote:

> OK, I've rebased the branch directly and force pushed ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/milessabin/shapeless/pull/334#issuecomment-76166703>.
>



-- 
Stacy

**Pull request closed without merging**
