### PR TITLE
HList.IndexOf / Coproduct.IndexOf type operation

### PR DESCRIPTION
**Pull request by ctongfei**
Implements HList.IndexOf[L, X], which returns a Nat that is the index of the first occurrence of X in HList L.

### CODE REVIEW

**Comment by milessabin** [comment]
That's great stuff! Thanks!

Before I merge ... would you mind adding the corresponding for `Coproduct`?

**Comment by ctongfei** [comment]
Coproduct.IndexOf added with accompanying tests.

**Comment by ctongfei** [comment]
Could you merge this now? I'd really like to use this in my project :-)

**Comment by milessabin** [comment]
I must have missed the notification for your more recent comment ... sorry :-(

Before I merge, could you tweak the tests to verify that the expected index type has actually been computed: as it stands you've provided the types explicitly ... we need to be sure that they will be inferred.

**Comment by ctongfei** [comment]
I wonder how I could write such a test.

**Comment by milessabin** [comment]
Maybe something closer to the expected usage? Code a user might write wouldn't hard code the resulting index.

**Comment by ctongfei** [comment]
Will do it in the next few days. Thanks :-)

**Comment by milessabin** [comment]
I don't want to merge this without a test that the expected types have been inferred.

**Pull request closed without merging**
