### PR TITLE
Add PartialComapped type class

### PR DESCRIPTION
**Pull request by Atry**

### CODE REVIEW

**Comment by Atry** [comment]
`PartialComapped` is like `Commaped`, except it skips elements that are not match `F[_]`.

**Comment by milessabin** [comment]
Looks interesting, but could you provide a motivating example?

**Comment by milessabin** [comment]
Still waiting for a motivating example.

**Comment by joroKr21** [comment]
There doesn't seem to be much interest in this. Feel free to reopen with a motivating example.
But in the end of the day we can't cover all typelevel functions so it's ok for some of them to live in user land.

**Pull request closed without merging**
