### PR TITLE
Support for runtime injection in Coproduct

### LINKED ISSUE #641: Support for runtime injection in Coproduct
As discussed in the [gitter channel](https://gitter.im/milessabin/shapeless?at=57ea4c8c54302caa6f2214cd), it would be nice to have the ability to inject runtime values of type `Any` in a `Coproduct`. This feature would improve the interoperability between shapeless coproducts and libraries that make an intensive use of untyped values like Akka.

A PR will be provided in short time.

### PR DESCRIPTION
**Pull request by juanjovazquez**
closes #641 

/cc @milessabin

### CODE REVIEW

**Comment by milessabin** [comment]
Aside from the failing test this looks spot on :-)

**Comment by juanjovazquez** [comment]
There must have to do with the the testing for Scala.js. I only tested for the JVM. I'll have a better look tomorrow with a fresh mind. Thanks.

**Comment by juanjovazquez** [comment]
Currently is only failing the testing on Sala 2.12.0-M5 because of some unrelated tests. 

```
[error] Failed: Total 556, Failed 4, Errors 0, Passed 552
[error] Failed tests:
[error] 	shapeless.LensTestsNat
[error] 	shapeless.LensTestsKey
[error] 	shapeless.AscribedOpticTestsDynamic
[error] 	shapeless.OpticTestsDynamic
```

**Comment by milessabin** [comment]
My sincere apologies for taking so long to respond to this ...

Could you rebase this and try again with 2.12.1?

**Comment by juanjovazquez** [comment]
Rebased. All tests passing now. Thanks!.

**Comment by milessabin** [comment]
Awesome! Thanks!

I'm bikeshedding a bit here, so please feel free to push back ... I'm not 100% sure about the "runtime" part of the name. Do you think "partial" might be a better alternative? ie. `PartialInject`/`partialInject`?

Other than that :+1: ...

**Comment by juanjovazquez** [comment]
I guess it must be because I've already got used to the name but I find the term `RuntimeInject` rather intuitive in this case. In any case, if you prefer, I can adapt the name. Other opinions would be valuable here.

**Comment by larsrh** [comment]
"Runtime" sounds good to me.

**Comment by larsrh** [comment]
I have taken the liberty to fix the merge conflicts.

**Comment by milessabin** [comment]
Apologies for taking so long to get back to this. OK, I'm fine with "runtime" ... if you rebase I'll merge ... thanks!

**Comment by juanjovazquez** [comment]
Rebased and working. Thanks!.

**Comment by milessabin** [comment]
Many thanks! Merging :-)

**Pull request merged**
