### PR TITLE
Remove GenTraversable constraint from ToSizedHList

### PR DESCRIPTION
**Pull request by ceedubs**
The instance method needs this sort of constraint, but I don't know of a
reason that the type class itself needs this constraint.

@tpolecat I think that you originally contributed this type class. What
do you think?

### CODE REVIEW

**Comment by ceedubs** [comment]
This is failing on a binary compatibility check. I'm not sure what the current policy and/or branching strategy is for that. I'll await further guidance.

**Comment by milessabin** [comment]
Unless anyone objects, I'd be happy to go with a MiMa exclusion for this one: I believe the bincompat issue would only be for other implementers of the type class trait, and I'd be surprised if there were any.

**Comment by ceedubs** [comment]
@milessabin agreed, I'd be surprised if there were any. But personally I also am not in a big rush to have this changed, so depending on the anticipated shapeless timeline maybe an exception isn't warranted. I'm fine either way -- do you want me to add an exception to the PR?

**Comment by milessabin** [comment]
It'd be great if you could add a MiMa exclusion to this PR :-)

**Comment by ceedubs** [comment]
@milessabin I've added the mima exception.

**Comment by milessabin** [comment]
Awesome ... thanks :-)

**Pull request merged**
