### PR TITLE
Add an example - recursion schemes for ADTs

### PR DESCRIPTION
**Pull request by joroKr21**
Inspired by Tim Williams' talk ["Recursion Schemes by Example"](https://youtu.be/Zw9KeP3OzpU).

The example shows how we can automatically generate a functor type and morphisms for an ADT.

### CODE REVIEW

**Comment by milessabin** [comment]
This is great stuff! Many thanks :-)

I know it's a pain, but do you think you could dig in to why it's not compiling on 2.10.x?

**Comment by joroKr21** [comment]
In 2.10 `ArrowAssoc` and `Ensuring` add an `x` member to anything via implicit conversion :grin:

**Comment by joroKr21** [comment]
Should be fixed now.

Hit some issues related to pattern matching and dependent types solved by using the `Aux` pattern.

**Comment by milessabin** [comment]
Awesome! Many thanks ... merging :-)

**Pull request merged**
