### PR TITLE
Reduce type loss in hlist ops with .Aux versions of inductive inputs

### PR DESCRIPTION
**Pull request by refried**
In the spirit of #650

### CODE REVIEW

**Comment by milessabin** [comment]
I'm fine with this, but could you deal with the coverage drop?

**Comment by refried** [comment]
Hm, even looking at the report, I have no clue why there is reduced coverage.  As a desperate move, I can try rebasing, but if that doesn't help, I'm not sure what to do.

**Comment by refried** [comment]
(just waking up) I see Github agrees there's only one different file vs master, so I don't think rebasing will help.  

Is there any chance Codecov is wrong?

**Comment by milessabin** [comment]
Hmm ... good point. If you rebase Codecov will rerun ... that might make the problem go away.

**Comment by refried** [comment]
Closing and reopening to try to trigger codecov again.  The current negative coverage delta doesn't make any sense to me, I didn't change any calls to code, only refined the types without breaking any tests.

**Comment by milessabin** [comment]
I've asked for help on the gitter channel ...

As far as I'm concerned this is a Codecov problem, not yours, but I'm going to hold off on merging a little longer in the hope that someone has an idea what's going on.

**Comment by dwijnand** [comment]
@travisbrown is also having coverage problems. He sees it as a scoverage problem (if it's the same problem).

https://github.com/circe/circe/pull/571

**Comment by refried** [comment]
Roger.

**Comment by milessabin** [comment]
Merging this now ... many thanks :-)

**Pull request merged**
