### PR TITLE
Add padTo method to HList

### PR DESCRIPTION
**Pull request by ryoppy**

### CODE REVIEW

**Comment by milessabin** [comment]
Great stuff!

Can you say why you've chosen to have pad with a length shorter than the unpadded list length return the list unchanged rather than being a compile time error? My gut feeling is that it would be more useful if when you pad to length _n_ you are guaranteed that the length of the resulting list is exactly _n_.

**Comment by ryoppy** [comment]
thank you for your comments!
I modified to return list has length exactly n.

**Comment by milessabin** [comment]
LGTM. Many thanks ... merging! :-)

**Comment by milessabin** [comment]
Could you send me another PR adding your details to the `CONTRIBUTORS` file?

**Comment by ryoppy** [comment]
thx!
I sent PR #518

**Comment by milessabin** [comment]
Thank you! :-)

**Pull request merged**
