### PR TITLE
osgification

### PR DESCRIPTION
**Pull request by FeiWongReed**
Hi.

You've osgified shapeless v2+, but there is no manifests for 1.2.x branch. But it's still widely used (by spray/parboiled v1), so could you accept my p/r and make a small release with manifests added into?

### CODE REVIEW

**Comment by milessabin** [comment]
I'm pretty reluctant to go back that far in time ... can't you use the spray build for shapeless >= 2.0.0?

**Comment by FeiWongReed** [comment]
Looks like that it's hard to build spray agains 2+.
I just created issue for spray developers, but if you may make small release for your v1 branch it will be priceless.

**Comment by milessabin** [comment]
A build of Spray for 2.x already exists,

  https://groups.google.com/forum/#!msg/spray-user/rxfjsg9OsUA/nytYALgIOn8J

**Comment by FeiWongReed** [comment]
Ok, thank you, but, anyway, could you at least accept P/R into old branch? Even without release?

**Comment by milessabin** [comment]
I've just been pointed at this: http://mvnrepository.com/artifact/io.spray/spray-routing-shapeless2_2.11/1.3.3.

Seriously, if there is any way for you to use a more recent release I would encourage you to do so.

**Comment by milessabin** [comment]
Have you had a chance to investigate using a shapeless 2.x build of spray yet?

**Comment by milessabin** [comment]
OK, closing for now.

**Pull request closed without merging**
