### PR TITLE
Add Discord badge

### PR DESCRIPTION
**Pull request by paualarco**
Making the Discord support channel more visible by adding a badge to #doobie that never expires :)

This is how it looks like:

Screen Shot 2021-05-14 at 00 32 06

### CODE REVIEW

**Review by milessabin — APPROVED** [review]
LGTM!

**Comment by joroKr21** [comment]
#doobie? I think the invite is to the Typelevel discord right?

**Comment by milessabin** [comment]
> #doobie? I think the invite is to the Typelevel discord right?

That's what it looked like to me.

**Comment by paualarco** [comment]
@joroKr21, @milessabin, sorry for the confusion, just opened the same PR for doobie before... actually the invite redirects you to the #shapeless channel directly :D

**Pull request merged**
