### PR TITLE
Typeclass to verify all elements of an hlist belong to a typeclass

### PR DESCRIPTION
**Pull request by triggerNZ**
This was suggested by @mpilquist on gitter. I found it useful, so thought I would PR it in. It is my first shapeless pull request, so any feedback is appreciated.

### CODE REVIEW

**Comment by milessabin** [comment]
Needs rebasing now ...

Would you mind reformatting to be more consistent with the rest of the source tree (essentially two space indent and break lines agressively).

Otherwise looks good. I'm not completely convinced by the name ... it's really something more like `Forall`, but I'm wary of using a name which is so generally useful. Also, we could have a similar definition for `Coproduct` which might also be useful.

**Comment by AlecZorab** [comment]
Also very useful, for whatever name you decide to go with, would be 

```
    def apply[F[_]] = new TypeclassInstancesAux[F]
    class TypeclassInstancesAux[F[_]] {def apply[In <: HList](in: In)(implicit ev: TypeClassInstances[F, In]) = ev}

    def apply[F[_], In <: HList](implicit ev: TypeClassInstances[F, In]) = ev
```

which I'm helpfully leaving in a comment instead of PRing @triggerNZ's branch because *lazy*

**Comment by triggerNZ** [comment]
@milessabin thank you for your comments. I did the rename. Are you okay with me doing the coproduct case in a seperate PR?

**Comment by triggerNZ** [comment]
@AlecZorab That's a cool addition - put it in

**Comment by milessabin** [comment]
LGTM. Many thanks ... merging :-)

**Comment by milessabin** [comment]
Yes, please do submit another PR for the coproduct case.

**Pull request merged**
