### PR TITLE
Introduced FieldType constructor on Witness

### PR DESCRIPTION
**Pull request by pchlupacek**
Just added simple addition to Witness syntax to allow arbitrary Union and Record Types. Modified Union tests to take benefits of this syntax. 
```scala
//before
Union.`'a -> Int, 'b -> String, 'c–>Double`.T
// now
Witness.`'a`.->>[Int] :+:  Witness.`'a`.->>[Int]  :+: Witness.`'a`.->>[Int]  :+: CNil
// -- or --
Witness.`'a`.Field[Int] :+:  Witness.`'a`.Field[Int]  :+: Witness.`'a`.Field[Int]  :+: CNil 

```

### CODE REVIEW

**Comment by alexarchambault** [comment]
About the changes in the tests, wouldn't it be better to keep the former tests (of the ``Union.`...`.T`` syntax), and only add tests of the new syntax along with it?

E.g. for the first test, I'm thinking of having something like
```scala
type U = Union.`'i -> Int, 's -> String, 'b -> Boolean`.T // former type, kept as is

// only additions
type U0 = Witness.`'i`.Field[Int] :+: Witness.`'s`.Field[String] :+: Witness.`'b`.Field[Boolean] :+: CNil
// ensures the new syntax gives the same result as the former one
implicitly[U =:= U0]
```

**Comment by pchlupacek** [comment]
@alexarchambault yeah perhaps you right for shorter types the previous syntax is more concise. I'll update this PR.

**Comment by milessabin** [comment]
Sorry if I'm being a bit dense, I can't quite see the benefits of this change ... as far as the examples of the tests are concerned, they offer the same functionality but are more verbose. So I agree with @alexarchambault that the existing tests should stay, but I'd also like to see something that demonstrates something new.

**Comment by pchlupacek** [comment]
@milessabin I'll just write a simple test that proves U =:= U0. As discussed on gitter, particular benefit of this is that we don't re-implement parser of the compiler (in backticks) and this allows us more complex contstruct and multi-line record/union types. It is not only beneficial in tests but anywhere where you need explicitly specify the type, for example in serialization/deserialization

Do I understand correctly that PR is ok, you just want to see different tests ?

**Comment by milessabin** [comment]
I really want to see a test of at least one compelling example that this PR enables that wasn't possible previously.

**Comment by pchlupacek** [comment]
@milessabin ok understood

**Comment by pchlupacek** [comment]
@milessabin @alexarchambault Just pushed change. LMK if the demonstration is ok or I need to put more examples....

**Comment by pchlupacek** [comment]
@milessabin not sure if you had chance to review this? If there is alternative to what this tries to achieve you like better, can you please share? Thanks.

**Comment by milessabin** [comment]
Yes, sorry about the hold up ... LGTM ... many thanks ... merging :-)

**Pull request merged**
