### PR TITLE
Added method modify to Zipper

### PR DESCRIPTION
**Pull request by petomat**

### CODE REVIEW

**Comment by milessabin** [comment]
Thanks. A couple of comments ...

Could you add a standalone op type class (which can be implemented in terms of `Get` and `Put` exactly as you have now) ... the rationale is that it's helpful to need only a single type class instance where these a propagated as implicit arguments through a series of nested calls.

And would you mind adding some tests?

**Comment by milessabin** [comment]
Oh, and then could you squash the resulting commit. Thanks :-)

**Comment by petomat** [comment]
I will do my best :-)

**Comment by petomat** [comment]
Sorry for the delay. I am still working on it...

**Comment by milessabin** [comment]
No worries :-)

**Comment by petomat** [comment]
@milessabin Would you mind having a look at my proposed commit? I hope it's close to what you have in mind.

**Comment by milessabin** [comment]
That looks absolutely spot on :-) Many thanks ... merging ...

**Pull request merged**
