### PR TITLE
Add left fold for Coproducts

### PR DESCRIPTION
**Pull request by AndreasKostler**
Left fold for Coproducts.

### CODE REVIEW

**Comment by ceedubs** [comment]
The constraint that the output of the `foldLeft`is `In` seems unnecessary to me.

It seems like as long as there is a `Case2[F, In, A]` for all A in the Codproduct, you should be able to return the output type of the matching `Case`. I'm guessing the current constraint is because of [this line](https://github.com/milessabin/shapeless/pull/425/files#diff-7f03e74196d53d11cd9f05dd6b87ac7cR387), but `case Inr` when the input is `H :+: CNil` is impossible, so we shouldn't need to support that case.

I don't think I articulated this particularly well. Feel free to ask me to clarify.

**Comment by AndreasKostler** [comment]
Not sure I understand you fully but I pushed a change to reflect what I *think* you mean ;)

**Comment by ceedubs** [comment]
Yes, this is exactly what I meant! :+1:

**Comment by AndreasKostler** [comment]
Awesome!

**Comment by milessabin** [comment]
Sorry it's taken me so long to get to this ... I've been bogged down with 2.12.0-M2 compatibility issues.

Anyhow, looks good :-) Many thanks ... merging!

**Pull request merged**
