### PR TITLE
Simpler ZipWithIndex

### PR DESCRIPTION
**Pull request by alexarchambault**
Fixes https://github.com/milessabin/shapeless/issues/490

Just a re-opening of https://github.com/milessabin/shapeless/pull/491.

Sorry for the noise :-|

### CODE REVIEW

**Comment by milessabin** [comment]
Is this is the same a the merge we just backed out?

**Comment by milessabin** [comment]
I mean, it LGTM ... I'm just puzzled why we backed it out before?

**Comment by jarreds** [comment]
I've confirmed that `zipWithIndex` is now compiling in a reasonable time for my use case. Code LGTM as well.

+1

**Comment by alexarchambault** [comment]
@milessabin I clicked *Merge* by mistake, I wanted to change a few things in it too...

**Comment by milessabin** [comment]
So is this ready for merge now?

**Comment by alexarchambault** [comment]
@milessabin Yep, it is.

**Comment by milessabin** [comment]
Awesome ... thanks folks! :-)

**Pull request merged**
