### PR TITLE
Publish scala-native snapshot artifacts

### PR DESCRIPTION
**Pull request by alexarchambault**
cc @xuwei-k

### CODE REVIEW

**Comment by alexarchambault** [comment]
On OS X, I'm getting errors like
```
[warn] Warnings
[warn] 000: No translation found for macro: range;[==,=+);${@}, in -----------------
[warn] Errors
[warn] 000: Invalid syntax for version: ${@}, for cmd: range, arguments; [range, [==,=+), ${@}]
[error] bnd: Invalid syntax for version: ${@}, for cmd: range, arguments; [range, [==,=+), ${@}]
[error] (coreNative/compile:doc) Scaladoc generation failed
```
if the scaladoc generation isn't disabled for native.

**Comment by schrepfler** [comment]
I think this would be really cool and enable a bunch of new stuff on the scala-native platform (example case-app.)

**Comment by milessabin** [comment]
I have to confess I'm not very happy with the effects the Scala Native stuff is having on the build. I think I'd like to see all the native publish stuff split out to a separate script. I'd also like some explanation of why 2.11.11 has been split out from the main matrix.

**Comment by alexarchambault** [comment]
@milessabin Updated the PR.

**Comment by milessabin** [comment]
@alexarchambault that's getting better. Would you mind moving the `before_install` stuff to an external script too? (sorry, I appreciate I'm asking you to tidy up someone else's work).

**Comment by milessabin** [comment]
Awesome! Many thanks :-)

**Pull request merged**
