### PR TITLE
Remove unnecessary macrocompat annotations

### PR DESCRIPTION
**Pull request by joroKr21**

### CODE REVIEW

**Review by milessabin — APPROVED** [review]
LGTM!

**Comment by milessabin** [comment]
Oh! Actually, [this](https://github.com/milessabin/shapeless/blob/series/2.3/core/src/main/scala_2.13-/shapeless/versionspecifics.scala#L47-L49) can go too ...

**Comment by joroKr21** [comment]
> Oh! Actually, this can go too ...

MiMa complains about that

**Comment by milessabin** [comment]
It's `private[shapeless]` though ... surely that's safe to remove?

**Comment by joroKr21** [comment]
> It's private[shapeless] though ... surely that's safe to remove?

We would have to add filters then. I'd rather keep it. WDYT?

**Comment by milessabin** [comment]
Why keep it? It's not accessible externally and you've removed all the internal uses ... surely it's just dead weight now?

**Comment by joroKr21** [comment]
> Why keep it? It's not accessible externally and you've removed all the internal uses ... surely it's just dead weight now?

It's less code / effort to keep the class than to add the filters. But ok you convinced me that it's better to remove it.

**Pull request merged**
