### PR TITLE
make Tagged a universal trait so tagging value classes works

### PR DESCRIPTION
**Pull request by kwark**
This fixes issue #644 

I also ran mima and it did not find any binary incompatible changes:

```
[IJ]> mimaReportBinaryIssues
[info] Resolving com.chuusai#shapeless_2.12;2.3.2 ...
[info] Resolving org.scala-lang#scala-library;2.12.0 ...
[info] Resolving org.typelevel#macro-compat_2.12;1.1.1 ...
[info] Resolving com.chuusai#shapeless_sjs0.6_2.12;2.3.2 ...
[info] Resolving org.scala-lang#scala-library;2.12.0 ...
[info] Resolving org.scala-js#scalajs-library_2.12;0.6.13 ...
[info] Resolving org.typelevel#macro-compat_2.12;1.1.1 ...
[info] Compiling 2 Scala sources to /Users/peter/dev/shapeless/core/jvm/target/scala-2.12/classes...
[info] Compiling 2 Scala sources to /Users/peter/dev/shapeless/core/js/target/scala-2.12/classes...
[info] Compiling 13 Scala sources to /Users/peter/dev/shapeless/core/jvm/target/scala-2.12/classes...
[info] Compiling 13 Scala sources to /Users/peter/dev/shapeless/core/js/target/scala-2.12/classes...
[info] Compiling 85 Scala sources to /Users/peter/dev/shapeless/core/jvm/target/scala-2.12/classes...
[info] Compiling 85 Scala sources to /Users/peter/dev/shapeless/core/js/target/scala-2.12/classes...
[info] coreJVM: found 0 potential binary incompatibilities while checking against com.chuusai:shapeless_2.12:2.3.2  (filtered 6)
[info] root: previous-artifact not set, not analyzing binary compatibility
[info] coreJS: found 0 potential binary incompatibilities while checking against com.chuusai:shapeless_sjs0.6_2.12:2.3.2  (filtered 6)
[success] Total time: 49 s, completed Dec 31, 2017 9:31:01 AM
```

### CODE REVIEW

**Comment by milessabin** [comment]
Thanks for this ... I'm _literally_ about to push the button on releasing 2.3.3, so this has missed the boat unfortunately.

This looks good, but we've made several attempts to improve things in this area before and they've all turned out to have downsides of one sort or another. I have a vague feeling that we've actually tried exactly this change previously ... would you mind going through the related PRs and issues and see if you can work out where things stand?

**Comment by kwark** [comment]
I have been going through some related PRs:

- The change for `Tagged` from a type alias to a trait was introduced by https://github.com/milessabin/shapeless/pull/20. The trait was not made universal because there was/is indeed no difference when looking at the decompiled bytecode with javap.
- https://github.com/milessabin/shapeless/issues/44 is still an issue, even when `Tagged` is made a universal trait.
- https://github.com/milessabin/shapeless/issues/557 is of course also still an issue, because it is a bug in scalac

I don't find any evidence that this specific change has been tried previously. 
I do acknowledge that this kind of change might inadvertently impact other areas of the shapeless codebase.

@milessabin I'll be happy to  check other PRs/issues. Do you have any specific in mind?

**Comment by joroKr21** [comment]
Needs rebase. Is there any reason not to do this? Looks like a no-brainer to me.

**Comment by milessabin** [comment]
> Is there any reason not to do this? Looks like a no-brainer to me.

Issues with 2.10 maybe?

**Comment by joroKr21** [comment]
We dropped 2.10 🎉

**Pull request merged**
