### PR TITLE
Use Scala Native JUnit plugin

### PR DESCRIPTION
**Pull request by armanbilge**
Backport of https://github.com/typelevel/shapeless-3/pull/88#discussion_r878391906.

I think it would be helpful to get a release with this fix, I was running into some conflicting dependency problems downstream. Thanks!

### CODE REVIEW

**Review by joroKr21 — APPROVED** [review]

**Comment by milessabin** [comment]
OK, merged.

@armanbilge bearing in mind that shapeless 2 is `epoch.major.minor` ... is this a minor or a major version bump for the release?

**Comment by armanbilge** [comment]
This seems fine as a minor. It's essentially just fixing metadata.

**Comment by armanbilge** [comment]
For prior art, Seb made a similar release as patch:
https://github.com/portable-scala/portable-scala-reflect/releases/tag/v1.1.2

**Comment by armanbilge** [comment]
@milessabin polite bump on a release for this? :)

**Comment by joroKr21** [comment]
Oh I didn't realise we needed a release 👍

**Comment by joroKr21** [comment]
Any idea why #1267 failed? 🤔

**Comment by joroKr21** [comment]
I did some cleanup and finally released 🚀

**Comment by armanbilge** [comment]
Thanks!

**Pull request merged**
