### PR TITLE
Slice and select items

### PR DESCRIPTION
**Pull request by AndreasKostler**
Implements #443
Implements #445
For your review

### CODE REVIEW

**Comment by milessabin** [comment]
Good stuff! Thanks :-)

I have a couple of naming quibbles. The term "item" isn't used anywhere else in shapeless, so it sticks out a little. I suggest renaming to `selectMany` (and renaming the op type class to `SelectMany` as well). And I think it would be better to rename `slice` to `selectRange`.

I'd also prefer it if you also defined a trivial `SelectRange` type class (which can be implemented entirely in terms of `Range` and `SelectMany`) so that `selectRange` has just a single implicit argument ... this makes it easier for someone using `selectRange` in the body of a method to propagate the required evidence from the outside.

**Comment by AndreasKostler** [comment]
Done

**Comment by milessabin** [comment]
Awesome :-)

One last thing ... if you define and use the `Nat` arguments in [this style](https://github.com/milessabin/shapeless/blob/master/core/src/main/scala/shapeless/syntax/hlists.scala#L101),

```scala
def at(n : Nat)(implicit at : At[L, n.N]) : at.Out = at(l)
```

rather than specifying them as an argument of a type variable bounded by `Nat` then it's possible to use ordinary `Int` literals (ie 0, 1, 2) rather than `Nat` literals (_0, _1, _2). Also if you look a couple of lines above where I linked you'll see that the convention is to have two variants: one which takes a `Nat` value argument as above, and one which take a type argument (but no corresponding value argument). It would be quite nice to keep to that convention.

**Comment by AndreasKostler** [comment]
I have added support for `Int` literals to the syntax functions for `selectRange` 
Unfortunately, I can't see how supporting a `List[Int]` for `selectMany` could be done easily. Is there a type class supporting the conversion from a `List[Int]` to a `HList <: Nat`?

**Comment by milessabin** [comment]
Sorry about the confusion over `selectMany` ... you're right that there isn't anything currently in shapeless that will lift an argument list of `Int` literals to an `HList` of `Nat`.

We can replace the value argument with an explicit type argument however, so instead of writing,
```scala
selectMany(_2 :: _3 :: _5 :: HNil)
```
you could write,
```scala
selectMany[_2 :: _3 :: _5 :: HNil]
```

This eliminates the need for the value at runtime altogether, and is (a little) more consistent with `at`.

At some point we might add support for lifting an argument list of `Int` literals to an `HList` of `Nat` in which case `selectMany` could be made completely consistent with `at` and `selectRange` (in fact, if you wanted to take a look at that that would be awesome :-) ).

**Comment by AndreasKostler** [comment]
Ok, will do. I will open a new ticket.

**Comment by AndreasKostler** [comment]
All the pieces are in place now. However, I am a bit stuck making `selectMany` consistent with `at` and `selectRange`...any help is appreciated.

**Comment by milessabin** [comment]
This looks good to me ... many thanks ... merging :-)

**Pull request merged**
