### PR TITLE
ToInt macro

### PR DESCRIPTION
**Pull request by eugengarkusha**
Currently the Nat numbers materialization has a runtime cost.

Proposed solution :  
1)eliminates run time cost
2)increases compile time performance

### CODE REVIEW

**Comment by eugengarkusha** [comment]
codecov complains on 'toIntSucc'method which is kept only for binary compatibility , marked as deprecated and never supposed to be invoked .
Is it considered safe to keep it uncovered(because covering it will look strange)?

**Comment by milessabin** [comment]
I think you should drop the `@deprecated` ... no ever explicitly called this method anyway, so about the only thing it's doing is causing trouble here.

**Comment by eugengarkusha** [comment]
yes, right

**Comment by milessabin** [comment]
My sincere apologies for taking so long to review and merge this.

Anyhow, LGTM. Many thanks ... merging :-)

**Comment by eugengarkusha** [comment]
Thanks!!

**Pull request merged**
