### PR TITLE
Define a typeclass `Perhaps` to reify implicit resolution failure

### PR DESCRIPTION
**Pull request by missingfaktor**
In a similar spirit as `OrElse`.

### CODE REVIEW

**Comment by milessabin** [comment]
I'm not opposed to this in principle, however, I think you can get pretty much the same effect by giving a (normal, language built-in) default value for your implicit argument ... does this PR cover any cases that can't be handled that way?

**Comment by missingfaktor** [comment]
Nothing really. It encapsulates that pattern in a data type is all. It may be useful when used in conjunction with other similar types. For instance, `ev: A OrElse Perhaps[B]`, something that will be harder to do otherwise.

**Comment by missingfaktor** [comment]
Actually never mind... In my last example, you could get the same effect with `A OrElse B = null`. 

Happy to close the PR if you don't think this adds much.

**Comment by milessabin** [comment]
It's a nice idea, but TBQH I don't really think it adds enough. Thanks anyhow :-)

**Pull request closed without merging**
