### PR TITLE
Added documentation for some user-visible classes in generic.scala

### PR DESCRIPTION
**Pull request by xoltar**
I have some docs for other files as well, submitting PRs on file-by-file basis to keep reviews manageable.

### CODE REVIEW

**Comment by milessabin** [comment]
Many thanks for that! Merging ... :-)

**Comment by milessabin** [comment]
Be sure to add yourself to the contributors file in the next PR ...

**Comment by milessabin** [comment]
One thing cropped up on the [PR build](https://travis-ci.org/milessabin/shapeless/jobs/70712690) ... various names in the doc were accidentally picked up as substitutions because they contained '$'s and there were a couple of other places where names were used in contexts which scaladoc expected to be able to find definitions but couldn't, typically because of lack of prefix information. Running the doc task from the SBT REPL is the quickest way to catch these things.

I've fixed the problems [here](https://github.com/milessabin/shapeless/commit/8a984c7941fe5f0c05fbc645c68597084ed69115) and also simplified the various `Repr` types ... these aren't the way they would be rendered on the REPL, but they are a lot easier to read.

**Comment by xoltar** [comment]
Good to know, thanks! Will run the doc task next time.

**Comment by fthomas** [comment]
Ideally the Travis build should catch such errors by running both the `test` and `doc` tasks. In Cats we added a command alias for validating PRs (https://github.com/non/cats/blob/aec71b97dfbe5b3e1c8e909805fb45b4451504b3/build.sbt#L219) which is used for Travis builds and which can be used by contributors before they send PRs.

**Comment by milessabin** [comment]
Agreed. PR? ;-)

**Pull request merged**
