### PR TITLE
Add the FillWith type class	

### PR DESCRIPTION
**Pull request by Atry**
This is a continuation of https://github.com/milessabin/shapeless/pull/593

### CODE REVIEW

**Comment by milessabin** [comment]
Looks good! Would you mind moving your name and contact details to the CONTRIBUTORS file and leave just your name in the `@author` scaladoc tag. And then could you squash the commits. Thanks!

**Comment by Atry** [comment]
IIRC, recently Github added feature of merging with squash

**Comment by milessabin** [comment]
Yup. I prefer to keep the merge commits.

**Comment by milessabin** [comment]
LGTM. Many thanks ... merging :-)

**Pull request merged**
