### PR TITLE
Improve error message by adding @implicitNotFound

### PR DESCRIPTION
**Pull request by Atry**

### CODE REVIEW

**Comment by milessabin** [comment]
Thanks!

I think the message would be a little clearer if it were worded as follows: "could not find Lazy implicit values for all of the types enumerated in ${T}".

**Comment by Atry** [comment]
You are right, though I still wonder if there is a solution that report the specific type not found in `T`.

**Comment by milessabin** [comment]
I think if you use Typelevel Scala with `-Yinduction-heurisitcs` you should get a more informative error message ... give it a try.

**Comment by milessabin** [comment]
Sorry, this seems to have slipped through the cracks ... many thanks ... merging :-)

**Pull request merged**
