### PR TITLE
product length is Nat

### PR DESCRIPTION
**Pull request by AndreasKostler**

### CODE REVIEW

**Comment by milessabin** [comment]
Given that there's a [workaround](https://github.com/milessabin/shapeless/issues/624#issuecomment-236359843) I think I'd like to be very confident that it's safe to add a MiMa exclusion rule for the bincompat failure that this introduces.

Would you mind generating a binary which exercising `ProductLength` with 2.3.1 then run (without recompilation) it again with a shapeless build which includes this fix. If it's fine then we can add the MiMa rule. If it isn't we'll need to postpone this until 2.4.0.

**Comment by AndreasKostler** [comment]
Miles, I am a bit lost. What do I need to do?

**Comment by milessabin** [comment]
Try something like this ...

 1. Put together a minimal sbt project which exercises `length` compiled against 2.3.1.
 2. Build a version of 2.3.1 with your change included.
 3. Run the binaries built in (1) using the binaries built in (2).

 That will test backwards binary compatibility (old code successfully links to new library). We also need to test forward binary compatibility (new code successfully links to old library). For that ...

 4. Locally publish a version of 2.3.1-SNAPSHOT with your change included.
 5. Build the project from (1) against 2.3.1-SNAPSHOT.
 6. Run the binaries build in (5) using the standard published 2.3.1.

**Comment by milessabin** [comment]
Am I dreaming, or has this PR (and some others) mysteriously come back from the dead?

**Comment by AndreasKostler** [comment]
I think it's never been dead really - more like undead. Given it breaks binary compat should this be postponed to 2.4.0?

**Comment by milessabin** [comment]
Yes, I think so ...

**Comment by joroKr21** [comment]
@AndreasKostler sorry for the long wait.
2.4.0 is coming soon. Care to rebase this PR?

**Comment by joroKr21** [comment]
Thanks for the contribution! Merged in #973

**Pull request closed without merging**
