### PR TITLE
fix typo in union example

### PR DESCRIPTION
**Pull request by joprice**

### CODE REVIEW

**Comment by milessabin** [comment]
Good spot ... many thanks ... merging :-)

**Comment by joprice** [comment]
By the by, have you considered using https://github.com/tkawachi/sbt-doctest to keep things like this in check?

**Comment by milessabin** [comment]
@joprice Yes, that would be useful ... PR?

**Comment by joprice** [comment]
I took a stab at it. I'm getting this in the coproduct examples:

```
could not find implicit value for parameter gen: shapeless.Generic[this.Animal]
```

The code is extracted into a test case in src_managed and run inside the constructor of an anonymous org.scalacheck.Properties instance. Perhaps defining them as inner classes trips up `knownDirectSubclasses`?

**Pull request merged**
