### PR TITLE
add Map toRecord method

### PR DESCRIPTION
**Pull request by tbfenet**
Add toRecord operation that fills a record with values from a map. Supports nested records

### CODE REVIEW

**Comment by milessabin** [comment]
Sorry it's taken me so long to give this proper attention.

It looks really interesting and useful ... I can some interesting directions it could go in.

One observation is that shapeless record types aren't the most convenient things to work with directly ... typically they would arise from the use of a shapeless `Generic` for an ADT. That suggests that it might also be worthwhile to consider handling shapeless unions, ie. labelled `Coproduct`s as well as records so that you can handle not just case classes, but sealed families of case classes.

If you went down that route, then I think what you have would be a form of serialization library where we're serializing to/from very loosely typed Scala (or even Java) data structures, but in a boilerplate-free and type safe way. I think that something like that would potentially be very useful and widely applicable.

I also think that similarly to other shapeless-based serialization libraries, like Scodec, argonaut-shapeless and spray-json-shapeless, it would be better as a standalone project than included directly in shapeless itself. I'm currently trying to work out how to extract out an essential core from shapeless and will be moving things like the lenses, scrap your boilerplate and zippers to separate projects and I would recommend the same here.

Let me know what you think ...

**Comment by tbfenet** [comment]
I just found no convenient way to populate records from loosely typed scala. Unlike plain HList where we  have toHList.  I am using Records to define the mapping of case classes in spark to data stored in Hive tables and this main issue I faced

**Comment by milessabin** [comment]
The analogy with `toHList` is quite persuasive. I've taken another look at the PR and I'm still not completely comfortable with it though. The nesting of `Map[Any, Any]` and use of `Either` rather than `Option` makes it feel like this is more of an application-specific thing rather than a low level primitive.

I'd be happy with something along these lines as an example, but I think that to include it in the main library I'd like to see if some simpler primitive can be extracted out of it. For instance do you think you could pull out a one-layer part of this (ie. convert a map to an option of record, but without recursing through nested maps) and then reconstruct the full nested conversion in terms of that?

**Comment by tbfenet** [comment]
The use of Either comes from experience when using toHList where I have had to resort to using a debugger to work out which field did not match. Here we are at the interface between runtime and compile time so I think the need to be some sort of hook for runtime diagnostics.  We could populate record from function instead of a Map? This might be a better primitive for different serialisation libraries.

**Comment by milessabin** [comment]
> We could populate record from function instead of a Map? This might be a better primitive for different serialisation libraries.

Could you elaborate on that a little? I'm used to the idea of a `Map[K, V]` corresponding to a function `K => V` but in that case we lose the ability to enumerate the keys, so I'm not quite sure how the mapping to a record might work.

**Comment by tbfenet** [comment]
It is driven from the record side. You use the the function to resolve all keys in record as it currently does using the Map.

**Comment by milessabin** [comment]
I understand your point of view, but I'm still not convinced. I can see a few ways to move this forward,

+ You could follow my suggestion above and make this a one-layer `Map` -> record operation (ie. no recursion through embedded maps) and switch to `Option` for consistency with `toHList`. I'd be happy to merge that into shapeless core. I'd also be happy to have an example (in the examples subproject) using this as a primitive to build the recursive version.

+ You could make the whole thing an example (in the examples subproject) as a specific idiom someone using Spark might need. This way, other people who have the same use case can benefit from the example, but it won't create confusion with other shapeless code.

+ You could create a new library that is specialized to the kind of problem you needed to solve (e.g. using shapeless + Spark), or add it to another library along those lines, maybe [frameless](https://github.com/adelbertc/frameless)?.

I hope you'll go for the first option, because I think that a one-layer `toRecord` operation that's consistent with the rest of shapeless would be a very welcome addition :-)

**Comment by milessabin** [comment]
Oh wow! I didn't see that you'd updated this PR with that last commit :-(

This looks good to merge now ... there are a couple of layout issues which can be fixed up later, but nothing that prevents this going in at long last.

My apologies for not noticing your update :-(

**Pull request merged**
