### PR TITLE
Add new adjoin type class

### PR DESCRIPTION
**Pull request by travisbrown**
This is an initial sketch of an implementation of the type class described in #413 (unified for `HList` and `Coproduct`). There was [some discussion of the name on Gitter](https://gitter.im/finagle/finch?at=5582eb321c3ba5ef5bff10db) this morning. I don't think "adjoin" is perfect, but IMO it's better than the alternatives (with "concat", "abut", "smash", and "conjoin" as the runners up).

I can add some documentation, examples, etc. this evening—I just wanted to get something up sooner rather than later.

### CODE REVIEW

**Comment by milessabin** [comment]
Given the implementation style, it would seem fairly natural to generalize this beyond the binary case ... thoughts?

I'm also thinking that this looks like something that belongs in the `ops` package, possibly with methods defined on the `HList` and `Coproduct` syntax traits?

**Comment by travisbrown** [comment]
It works beyond the binary case now—that's just not represented in the tests (but should / will be). Where are you imagining it'd live under `ops`? I agree that it would make sense for it to be there, but it cuts across the current organization, in that it doesn't fit in either `hlist` or `coproduct`.

**Comment by milessabin** [comment]
Oh! Sorry :-) 

I thing it can live in its own ops.align object for now.

**Comment by vkostyukov** [comment]
What do you think about `Flatten`instead of `Adjoin`? Looking at the implementation it reminds me Scala's `.flatten`. Eg: `List(List(1), List(2), 3, 4).flatten = List(1, 2, 3,4)`.

**Comment by milessabin** [comment]
That's a reasonable suggestion, but I think we're too used to the idea that `flatten` is equivalent to `flatMap(identity)` which is already defined for `HList` with subtly different semantics.

**Comment by travisbrown** [comment]
I've started a simplified version of Finch's `Router` that I'm going to add to the examples here, but it's not quite done. If this type class doesn't make it into 2.2.3 that's not a big deal—it'd be nice to be able to use this in Finch 0.8.0, but not necessary if the timing doesn't work out.

**Comment by milessabin** [comment]
I think there's only one thing I want to change here now: I'd rather the examples had asserts than printlns: partly so regressions can be caught, but mainly so that a casual reader can see what the expected result is without have to actually run the example.

It's not a blocker for merging, but I have a few things to do this morning so I'll leave it here on the offchance that you'll be able to deal with that before I come back to it. No worries if not.

**Comment by milessabin** [comment]
Awesome ... thanks :-) Merging.

**Pull request merged**
