### PR TITLE
Link to the active mailing list in the README

### PR DESCRIPTION
**Pull request by DanielleSucher**
Since shapeless-dev seems active nowadays, and the typelevel mailing list does not. ^^

### CODE REVIEW

**Comment by milessabin** [comment]
Hi Danielle. Actually shapeless-dev is deprecated in favour of the typelevel list.

Really all the discussion happens on [gitter](https://gitter.im/milessabin/shapeless) nowadays, so both are pretty much tumbleweed ...

**Comment by DanielleSucher** [comment]
Fair enough! I just didn't see any activity on the typelevel list since last year, but activity on shapeless-dev even over the past few days.

**Comment by milessabin** [comment]
I'll take that as a reminder to post a message to the shapeless list pointing people in the right direction ... thanks :-)

**Comment by DanielleSucher** [comment]
And maaaaaybe remove links to all deprecated mailing lists here? :stuck_out_tongue: 

(Feel free to close this pr, obvs. ^^)

**Comment by milessabin** [comment]
Err ... I thought they were already gone? Where do you see them?

**Comment by DanielleSucher** [comment]
Sorry, I was just referring to the typelevel list links because of your "so both are pretty much tumbleweed" comment!

**Comment by non** [comment]
Right, possibly something like "Questions are best asked on Gitter, where most discussion is happening these days. The (mostly-dormant) email list can be found at..."

**Comment by non** [comment]
*(makes a note to adjust the language on spire's README as well)*

**Comment by milessabin** [comment]
Yes, I guess so. Perhaps we should close those lists for posting altogether?

**Comment by milessabin** [comment]
Right, I think this is addressed now in dc7f5e3112f3fbac68f9de7b51da39cba0cab11e and a88b76f14e98e2c1152362a57527720cae2a05bd. Thanks for raising the issue :-)

**Pull request closed without merging**
