### PR TITLE
Fixed semiauto derivation of Default instances

### LINKED ISSUE #747: Implicit Default[] instantiation fails when base trait with abstract method is used for companion object
The following example doesn't compile with Scala 2.11 and shapeless 2.3.2 (implicit Default[Sample] not found):

```scala
case class Sample(a: Int)
trait Companion {
  def default: Default[Sample]
}
object Sample extends Companion {
  val default = Default[Sample]  // Error: No Default[Sample] found
}
```

The compile error is triggered by defining the default method in the base trait and implementing it as a `val` in the object that derives from the trait. One of the following changes makes the code compile:
  
  * Removing the method in the base trait
  * Adding an explicit type for the val; e.g. `val default: Default[Sample] = ...`
  * Changing the `val` to a `def`
 
The code compiles with Scala 2.12.3.

### PR DESCRIPTION
**Pull request by joroKr21**
Achieved via refactoring of `DefaultMacros.materialize`.

Fixes #747

### CODE REVIEW

**Comment by joroKr21** [comment]
Some missing functionality in Scala 2.10 makes things more verbose. Depending on how #655 turns out, `DefaultMacros` can be simplified at a later point (probably true for other macros as well).

**Comment by milessabin** [comment]
LGTM! Many thanks ... merging :-)

**Comment by milessabin** [comment]
Although Travis showed this as green previously, rerunning the build after clearing the build caches results in a build failure on 2.10.x: https://travis-ci.org/milessabin/shapeless/builds/274500921.

Would you mind taking a look?

**Comment by joroKr21** [comment]
This looks like a spurious error. I saw it in #765 but I couldn't reproduce it locally. The failing example has nothing to do with `Default`. This commit fixes the build: a531c48ef00df82b19c046828e5c0fea5fb3d305

**Comment by milessabin** [comment]
Could you pull that commit out as a separate PR?

**Pull request merged**
