### PR TITLE
MkString on HList was overconstrained

### PR DESCRIPTION
**Pull request by Jacoby6000**

### CODE REVIEW

**Comment by milessabin** [comment]
Looks good, but unfortunately not binary compatible.

I don't know if it's worth it, but I think a binary compatible alternative would be to use the existing signature, but give the implicit parameter a `null` default value and implement as you have done here.

**Comment by Jacoby6000** [comment]
A binary compatible alternative wouldn't be any more useful than the
existing implementation.

**Comment by Jacoby6000** [comment]
Oh my bad. I didn't read your entire message. It's late 😅  I'll try that tomorrow.

**Comment by milessabin** [comment]
Looks good ... maybe add a comment to the effect that the implicit parameter list should be removed in the next binary compatibility breaking release?

**Comment by Jacoby6000** [comment]
@milessabin done!

**Comment by milessabin** [comment]
LGTM ... many thanks ... merging :-)

**Pull request merged**
