### PR TITLE
adding Coproducts and Generic to some constraints

### PR DESCRIPTION
**Pull request by wheaties**
I went ahead with adding both generic and Coproduct instances to some of the various constraints. Comments about this PR:
1. I did not add Coproduct instances to Key or Value constraints. I've not used Shapeless Unions before and didn't know how much value it might add. Can always be another PR.
2. For the life of me, I can't get `Const[Foo]#ƛ` to work with anything involving `UnaryTCConstraint` and `Generic`.
3. I moved things that were no longer just "HList" constraints to a "constraints" file. Ditto for the unit tests.

### CODE REVIEW

**Comment by milessabin** [comment]
My sincere apologies for not having responded to this before. This breaks binary compatibility, so it will have to wait for 2.4.0, but otherwise it LGTM. Many thanks.

**Comment by wheaties** [comment]
No problem Miles. Would there be any value to adding in anything for shapeless Union types here?

**Comment by milessabin** [comment]
What did you have in mind for unions?

**Comment by wheaties** [comment]
Same corollary as that from hist to record types as we have from coproduct to union.

**Comment by milessabin** [comment]
Ahh ... yes, of course. Yup, adding instances for unions would make sense too.

**Comment by wheaties** [comment]
Rebased on 2.3.3. Sept of 2016! LOL, this is nearly 2yrs old. How time flies when you're having kids/fun.

**Comment by milessabin** [comment]
Many thanks for your persistence with this.

**Comment by wheaties** [comment]
I'll look to rebase and/or open up a new PR given the activity these past few days.

**Comment by joroKr21** [comment]
> I'll look to rebase and/or open up a new PR given the activity these past few days.

Many thanks 👍 Working to clean up the 2.4.0 milestone so we can release.
This can definitely make it in.

**Comment by wheaties** [comment]
Closing this and being replaced with another PR.

**Pull request closed without merging**
